version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda functions..."
      - cd "Lambda Functions/index-photos"
      - zip -r ../../index-photos.zip .
      - cd ../search-photos
      - zip -r ../../search-photos.zip .
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
