version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda functions..."
      - cd "Lambda Functions"
      - zip ../index-photos.zip "index-photos.py"
      - zip ../search-photos.zip "search-photos.py"

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
